### ISSUE TITLE
Font - Turkce karakter sorunu

### ISSUE THREAD

**Issue by ergenekonyigit** [abdullahvelioglu/vizgi#1]
OS X 10.11.4 Safari 9.1 surumunde turkce karakterler patliyor.

![image](http://i.imgur.com/0RUyJ53.png)

**Comment by abdullahvelioglu** [comment]
Bu hatayı bana bildirdiğin için teşekkür ederim. Bu gibi onlarca hata ile karşılaşıyorum. Uygun zamanda optimizasyonlarını yapacağım.
